apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmanagedclusters-aws
  labels:
    provider: aws
spec:
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: aws-roles-env
  compositeTypeRef:
    apiVersion: devops.com/v1alpha1
    kind: XManagedCluster

  resources:
    - name: eks-cluster-main
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: Cluster
        spec:
          providerConfigRef:
            name: aws-primary-config
          forProvider:
            region: eu-west-3
            version: "1.32"
            roleArn: ""
            vpcConfig:
              - subnetIds: []
          writeConnectionSecretToRef:
            name: ""
            namespace: crossplane-system

      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromEnvironmentFieldPath
          fromFieldPath: clusterRoleArnRef
          toFieldPath: spec.forProvider.roleArn
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.vpcConfig[0].subnetIds

    - name: eks-nodegroup
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: NodeGroup
        spec:
          providerConfigRef:
            name: aws-primary-config
          forProvider:
            region: eu-west-3
            nodeRoleArn: ""
            scalingConfig:
              - desiredSize: 2
                maxSize: 3
                minSize: 1
            instanceTypes:
              - "t3.micro"
            subnetIds: []

      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.clusterName
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.subnetIds
        - type: FromEnvironmentFieldPath
          fromFieldPath: nodegroupRoleArnRef
          toFieldPath: spec.forProvider.nodeRoleArn