apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmanagedclusters-aws
  labels:
    provider: aws
spec:
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: aws-roles-env
  compositeTypeRef:
    apiVersion: devops.com/v1alpha1
    kind: XManagedCluster
    
  resources:
    # --- 1. EKS CLUSTER (Control Plane) ---
    - name: eks-cluster-main
      base:
        apiVersion: eks.aws.upbound.io/v1beta1 
        kind: Cluster
        spec:
          providerConfigRef:
            name: aws-primary-config 
          forProvider:
            region: eu-west-3 
            version: "1.32" # EKS ne supporte pas encore 1.32, nous revenons à la version stable testée
            roleArn: "" # Sera injecté depuis EnvironmentConfig (clusterRoleArnRef)
            vpcConfig:
              - subnetIds: [] # Patché depuis le XR (spec.subnetIds)
          writeConnectionSecretToRef:
            name: "" # Patché depuis le XR (spec.id)
            namespace: crossplane-system
            
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromEnvironmentFieldPath
          fromFieldPath: clusterRoleArnRef
          toFieldPath: spec.forProvider.roleArn
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.vpcConfig[0].subnetIds

    # --- 2. EKS NODE GROUP (Workers) ---
    # AJOUTÉ ICI pour que les pods Nginx puissent démarrer (corrige le statut Pending)
    - name: eks-nodegroup
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: NodeGroup
        spec:
          providerConfigRef:
            name: aws-primary-config
          forProvider:
            region: eu-west-3
            # nodeRoleArn injecté depuis EnvironmentConfig (nodegroupRoleArnRef)
            nodeRoleArn: ""
            scalingConfig:
              - desiredSize: 2 # 2 nœuds de travail
                maxSize: 3
                minSize: 1
            instanceTypes:
              - "t3.micro" # Type de machine
            subnetIds: [] # Patché depuis le XR (spec.subnetIds)

      patches:
        # Lie le NodeGroup au Cluster (en utilisant l'ID/Nom du XR)
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.clusterName
        # Utilise les MÊMES subnets que le cluster
        - fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.subnetIds
        - type: FromEnvironmentFieldPath
          fromFieldPath: nodegroupRoleArnRef
          toFieldPath: spec.forProvider.nodeRoleArn